from typing import Protocol

from domain.models import Job, PipelineEvent


class JobRepository(Protocol):
    async def save(self, job: Job) -> None: ...

    async def get(self, job_id: str) -> Job | None: ...

    async def find_by_chat(self, chat_id: int) -> Job | None: ...

    async def find_by_issue(self, issue_number: int) -> Job | None: ...

    async def find_by_event(self, event: PipelineEvent) -> Job | None: ...

    async def find_waiting_for_pr(self) -> Job | None: ...

    async def list_non_terminal(self) -> list[Job]: ...
